@startuml 聊天室示例图

object 用户A {
  +用户名: 张三
  +状态: 在线
  +消息: "大家好！"
  +时间: 5.20AM
}

object 用户B {
  +用户名: 李四
  +状态: 在线
  +消息: "你好，张三！"
  +时间: 13.00PM
}

object 用户C {
  +用户名: 王五
  +状态: 在线
  +消息: "你们好！"
  +时间: 14:00 PM
}

object 非凡聊天室 {
  +消息记录:
  "张三: 大家好！
   李四: 你好，张三！
   王五: 你们好！"
}

用户A --> 聊天室服务器 : 发送消息
聊天室服务器 --> 用户B : 转发消息
聊天室服务器 --> 用户C : 转发消息

用户B --> 聊天室服务器 : 发送消息
聊天室服务器 --> 用户A : 转发消息
聊天室服务器 --> 用户C : 转发消息

用户C --> 聊天室服务器 : 发送消息
聊天室服务器 --> 用户A : 转发消息
聊天室服务器 --> 用户B : 转发消息

@enduml
