@startuml
left to right direction
skinparam packageStyle rectangle
actor Customer
actor Enterprise as EnterpriseCustomer
rectangle "Bank App" {
usecase "Transfer" as Transfer
usecase "Check Balance" as CheckBalance
usecase "Financial Management" as FinancialManagement
usecase "Loan" as Loan
Transfer --> (System)
CheckBalance --> (System)
FinancialManagement --> (System)
Loan --> (System)
(Transfer) .> (System) : (Possible Exceed Limit)
(Loan) .> (System) : (Assess Assets)
(Loan) .> (System) : (Determine Loan Amount)
(Transfer) <-- (Customer)
(CheckBalance) <-- (Customer)
(FinancialManagement) <-- (Customer)
(Loan) <-- (Customer)
(Loan) <-- (EnterpriseCustomer)
}
@enduml