@startuml
|用户A|
start
:登录聊天室;
|用户B|
:登录聊天室;
|用户C|
:登录聊天室;

|用户A|
:发送消息;
|聊天室服务器|
:接收消息;
:将消息转发给用户B和用户C;

|用户B|
:接收消息;
:显示消息;

|用户C|
:接收消息;
:显示消息;

|用户B|
:发送消息;
|聊天室服务器|
:接收消息;
:将消息转发给用户A和用户C;

|用户A|
:接收消息;
:显示消息;

|用户C|
:接收消息;
:显示消息;

|用户C|
:发送消息;
|聊天室服务器|
:接收消息;
:将消息转发给用户A和用户B;

|用户A|
:接收消息;
:显示消息;

|用户B|
:接收消息;
:显示消息;

@enduml