@startuml
start

:用户进入聊天室;
:显示之前的聊天记录;
:显示当前在线人数;

:用户在聊天输入框中输入消息;
:用户点击发送按钮;

alt 消息包含@指定用户
    :高亮显示@通知给指定用户;
else 消息不包含@指定用户
    :普通消息处理;
end

:消息出现在聊天记录中;
:其他用户实时接收消息;

:刷新在线人数;
:更新聊天记录;

stop
@enduml
